tap 'homebrew/cask'
tap 'homebrew/cask-versions'

# Fonts
tap 'homebrew/cask-fonts'
cask 'font-hack'

cask '1password6'
cask 'firefox'
cask 'chromium'
cask 'skype'
cask 'slack'
cask 'inkscape'
cask 'zoom'
cask 'spotify'

# Programming Languages & tools
cask 'java'
brew 'gradle'
brew 'nvm'
brew 'leiningen'

# Development Tools
brew 'git'

# Cloud & CI
tap 'heroku/brew'
brew 'heroku'
brew 'heroku-node'
brew 'awscli'
cask 'docker'
brew 'circleci', args: ["ignore-dependencies"]
brew 'pulumi'

# IDEs & Helpers
cask 'intellij-idea-ce'
cask 'emacs'
brew 'multimarkdown'
brew 'shellcheck'
brew 'wakatime-cli'
